version: '3.5'  

services:
  proxy: 
    image: jwilder/nginx-proxy 
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80 

  frontend:
    container_name: frontend-26
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - proxy

  backend:
    container_name: backend-26
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - proxy
    volumes:
        - "./logs.txt:/mydir/backend-example-docker/logs.txt"

  db:
    container_name: postgres-26 
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example

  redis:
    container_name: redis-26
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"


